server.port : 8761
eureka.client.register-with-eureka : false
eureka.server.enableSelfPreservation: false

spring:
  cloud:
    discovery:
      blocking.enabled: true
      reactive.enabled: false        
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config
      fail-fast: false
      retry:
        initial-interval: 2000
        multiplier: 1.5
        max-attempts: 10
        max-interval: 30000